services:

  app:
    build:
      context: ./app
    container_name: app
    restart: unless-stopped
    env_file:
      - ./app/.env
    volumes:
      - ./app/src:/app/src
    depends_on:
      - database
      - rabbitmq

  worker-1:
    build:
      context: ./app
    container_name: worker-1
    command: python worker.py
    env_file:
      - ./app/.env
    environment:
      WORKER_ID: worker-1
    volumes:
      - ./app/src:/app/src
    depends_on:
      - rabbitmq
      - database

  worker-2:
    build:
      context: ./app
    container_name: worker-2
    command: python worker.py
    env_file:
      - ./app/.env
    environment:
      WORKER_ID: worker-2
    volumes:
      - ./app/src:/app/src
    depends_on:
      - rabbitmq
      - database

  web-proxy:
    build:
      context: ./web-proxy
    container_name: web-proxy
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  database:
    image: postgres:15
    container_name: database
    restart: always
    environment:
      POSTGRES_DB: ml_service_db
      POSTGRES_USER: ml_user
      POSTGRES_PASSWORD: ml_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  rabbitmq_data:
  postgres_data: